import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, AgentAnalysis, agentAnalyses, Holding, holdings, users } from "../drizzle/schema";
import { ENV } from "./_core/env";
let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb(){ if(!_db&&process.env.DATABASE_URL){try{_db=drizzle(process.env.DATABASE_URL)}catch(e){console.warn("[Database] Failed to connect",e);_db=null}} return _db; }
export async function upsertUser(user: InsertUser){if(!user.openId)throw new Error("User openId is required");const db=await getDb();if(!db){console.warn("[Database] unavailable");return}const values:InsertUser={openId:user.openId};const updateSet:Record<string,unknown>={};const fields=["name","email","loginMethod","username","passwordHash","mobileNumber","avatarUrl"] as const;for(const f of fields){if(user[f]!==undefined){values[f]=user[f]??null;updateSet[f]=user[f]??null}}if(user.lastSignedIn!==undefined){values.lastSignedIn=user.lastSignedIn;updateSet.lastSignedIn=user.lastSignedIn}if(user.role!==undefined){values.role=user.role;updateSet.role=user.role}else if(user.openId===ENV.ownerOpenId){values.role="admin";updateSet.role="admin"}if(!values.lastSignedIn)values.lastSignedIn=new Date();if(!Object.keys(updateSet).length)updateSet.lastSignedIn=new Date();await db.insert(users).values(values).onDuplicateKeyUpdate({set:updateSet})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return;const r=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return r[0]}
export async function getUserByUsername(username:string){const db=await getDb();if(!db)return;const r=await db.select().from(users).where(eq(users.username,username)).limit(1);return r[0]}
export async function updateUserProfile(userId:number,values:Pick<InsertUser,"name"|"email"|"mobileNumber"|"avatarUrl">){const db=await getDb();if(!db)throw new Error("Database is not configured");await db.update(users).set(values).where(eq(users.id,userId));const r=await db.select().from(users).where(eq(users.id,userId)).limit(1);return r[0]}
export async function listHoldings(userId:number){const db=await getDb();if(!db)return[];return db.select().from(holdings).where(eq(holdings.userId,userId)).orderBy(desc(holdings.updatedAt))}
export async function addHolding(userId:number,input:{symbol:string;quantity:number;averagePrice:string}){const db=await getDb();if(!db)throw new Error("Database is not configured");await db.insert(holdings).values({userId,symbol:input.symbol.toUpperCase(),quantity:input.quantity,averagePrice:input.averagePrice});return listHoldings(userId)}
export async function deleteHolding(userId:number,id:number){const db=await getDb();if(!db)throw new Error("Database is not configured");await db.delete(holdings).where(and(eq(holdings.id,id),eq(holdings.userId,userId)));return listHoldings(userId)}
export async function saveAgentAnalysis(input:{userId:number;symbol:string;provider:string;riskLevel:number;technical:string;fundamentals:string;sentiment:string;risk:string;synthesis:string}){const db=await getDb();if(!db)throw new Error("Database is not configured");await db.insert(agentAnalyses).values(input);return getLatestAgentAnalysis(input.userId,input.symbol)}
export async function getLatestAgentAnalysis(userId:number,symbol:string){const db=await getDb();if(!db)return;const r=await db.select().from(agentAnalyses).where(and(eq(agentAnalyses.userId,userId),eq(agentAnalyses.symbol,symbol))).orderBy(desc(agentAnalyses.createdAt)).limit(1);return r[0]}
