import { useEffect, useMemo, useState } from "react";

type RangeKey = "1D" | "1W" | "1M" | "1Y";
const rangeSize: Record<RangeKey, number> = { "1D": 96, "1W": 168, "1M": 30, "1Y": 52 };
type Point = { t: number; v: number };
export type MarketDeskChartProps = { symbol: string; sector: string; price: number; change: number; changePercent: number; volume?: string; history: Point[]; live: boolean };

function Sparkline({ points, onHover }: { points: Point[]; onHover: (index: number | null) => void }) {
  const width = 920; const height = 250; const values = points.map(point => point.v); const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1;
  const coords = points.map((point, i) => ({ x: (i / Math.max(points.length - 1, 1)) * width, y: height - ((point.v - min) / range) * (height - 32) - 16 }));
  const path = coords.map(point => `${point.x},${point.y}`).join(" ");
  return <svg className="md-chart" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-label="Live price history" onMouseMove={event => { const rect = event.currentTarget.getBoundingClientRect(); const index = Math.round(((event.clientX - rect.left) / rect.width) * Math.max(points.length - 1, 0)); onHover(Math.max(0, Math.min(points.length - 1, index))); }} onMouseLeave={() => onHover(null)}><defs><linearGradient id="md-fill-willow" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--chart-line)" stopOpacity=".24"/><stop offset="1" stopColor="var(--chart-line)" stopOpacity="0"/></linearGradient></defs><line x1="0" y1="52" x2={width} y2="52" className="md-grid-line"/><line x1="0" y1="125" x2={width} y2="125" className="md-grid-line"/><line x1="0" y1="198" x2={width} y2="198" className="md-grid-line"/><polygon points={`0,${height} ${path} ${width},${height}`} fill="url(#md-fill-willow)"/><polyline points={path} fill="none" stroke="var(--chart-line)" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}

function companyProfile(symbol: string) { const profiles: Record<string,{vol:number;drift:number;cycle:number}> = { RELIANCE:{vol:.008,drift:.00012,cycle:4.2}, TCS:{vol:.004,drift:.00022,cycle:7.4}, INFY:{vol:.011,drift:-.00004,cycle:3.1}, HDFCBANK:{vol:.005,drift:.00016,cycle:9.2}, ICICIBANK:{vol:.009,drift:.00018,cycle:5.6}, SBIN:{vol:.014,drift:-.00010,cycle:2.7} }; return profiles[symbol]??{vol:.008,drift:.00008,cycle:5.5}; }
function demoSeed(symbol: string, price: number, count: number, stepMs: number): Point[] { const profile=companyProfile(symbol); return Array.from({length:count},(_,i)=>({t:Date.now()-(count-1-i)*stepMs,v:price*(1+Math.sin(i/profile.cycle)*profile.vol+Math.cos(i/11)*profile.vol*.55+i*profile.drift)})); }
function createDemoRanges(symbol: string, price: number): Record<RangeKey, Point[]> { return { "1D": demoSeed(symbol,price,96,15*60*1000), "1W": demoSeed(symbol,price,168,60*60*1000), "1M": demoSeed(symbol,price,30,24*60*60*1000), "1Y": demoSeed(symbol,price,52,7*24*60*60*1000) }; }

export default function MarketDeskChart({ symbol, sector, price, change, changePercent, volume, history, live }: MarketDeskChartProps) {
  const [range, setRange] = useState<RangeKey>("1D"); const [hoverIndex, setHoverIndex] = useState<number | null>(null); const [demoRanges, setDemoRanges] = useState<Record<RangeKey, Point[]>>(() => createDemoRanges(symbol,price));
  useEffect(() => { if (!live) { setDemoRanges(createDemoRanges(symbol,price)); const timer = window.setInterval(() => { setDemoRanges(previous => { const next = { ...previous }; const currentPrice = previous["1D"].at(-1)?.v ?? price; const profile=companyProfile(symbol); const step = Math.sin(Date.now()/(profile.cycle*700))*profile.vol*.12 + Math.cos(Date.now()/4100)*profile.vol*.08 + profile.drift; const nextPrice = Math.max(1, currentPrice * (1 + step)); next["1D"] = [...previous["1D"], { t: Date.now(), v: nextPrice }].slice(-rangeSize["1D"]); (Object.keys(rangeSize) as RangeKey[]).filter(key => key !== "1D").forEach(key => { const series = previous[key]; next[key] = [...series.slice(0,-1), { ...(series.at(-1) ?? {t:Date.now(),v:nextPrice}), v: nextPrice }]; }); return next; }); }, 1800); return () => window.clearInterval(timer); } return undefined; }, [live, symbol]);
  const sourcePoints = live ? history : demoRanges[range]; const points = sourcePoints.slice(-rangeSize[range]); const displayPoints = points.length ? points : [{ t: Date.now(), v: price }]; const latest = displayPoints.at(-1)?.v ?? price; const previous = displayPoints.at(-2)?.v ?? price; const displayChange = live ? change : latest - previous; const displayPercent = live ? changePercent : ((latest - previous) / previous) * 100; const values = displayPoints.map(point => point.v);
  const yLabels = useMemo(() => { const max = Math.max(...values); const min = Math.min(...values); return [max, min + (max - min) * .66, min + (max - min) * .33, min]; }, [values]);
  const hovered = hoverIndex === null ? null : displayPoints[hoverIndex]; const tooltipLeft = hoverIndex === null ? 50 : (hoverIndex / Math.max(displayPoints.length - 1, 1)) * 100; const lastTrade = new Date(displayPoints.at(-1)?.t ?? Date.now()).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
  return <section className="market-desk-chart"><div className="md-head"><div><span className="md-kicker">LEAD INSTRUMENT · {range === "1D" ? "INTRADAY" : range === "1W" ? "7 DAYS" : range === "1M" ? "1 MONTH" : "1 YEAR"}</span><div className="md-instrument"><h2>{symbol}</h2><span>{sector}</span><i className={displayPercent >= 0 ? "positive" : "negative"}>{displayPercent >= 0 ? "+" : "−"}{Math.abs(displayPercent).toFixed(2)}%</i><button className="md-pin is-pinned">⌖ Pinned</button></div></div><div className="md-controls"><span className={`md-status ${live ? "online" : "demo"}`}><b /> {live ? "LIVE · UPSTOX" : "DEMO REAL-TIME"}</span><div className="md-ranges">{(Object.keys(rangeSize) as RangeKey[]).map(key => <button key={key} className={range === key ? "active" : ""} onClick={() => setRange(key)}>{key}</button>)}</div></div></div><div className="md-price"><strong>{latest.toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 })}</strong><span className={displayChange >= 0 ? "positive" : "negative"}>↗ {displayChange >= 0 ? "+" : "−"}₹{Math.abs(displayChange).toFixed(2)} {live ? "today" : "demo tick"}</span></div><div className="md-plot"><div className="md-y-axis">{yLabels.map((label, i) => <span key={i}>{Math.round(label).toLocaleString("en-IN")}</span>)}</div><div className="md-chart-wrap"><Sparkline points={displayPoints} onHover={setHoverIndex}/>{hovered&&<div className="md-tooltip" style={{left:`clamp(54px,${tooltipLeft}%,calc(100% - 54px))`}}><b>{hovered.v.toLocaleString("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2})}</b><span>{new Date(hovered.t).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})}</span></div>}</div></div><div className="md-footer"><span><b className="md-dot"/> {live ? "Live price" : "Demo data"}</span><span>VWAP <strong>{live ? "Provider data" : "Demo reference"}</strong></span><span>Volume <strong>{volume ?? "Demo stream"}</strong></span><span>Updated <strong>{lastTrade}</strong></span></div></section>;
}
